### ISSUE TITLE
稍大的plist文件会报错，无法生成文件

### ISSUE THREAD

**Issue by lewisun7** [zilongshanren/unpack-textureatlas#2]
2018-06-14T14:26:16.431Z - error: Error: Invalid edge extension [object Object]
    at Sharp.extend (C:\CocosCreator\CocosCreator_v1.10.0-rc.1\resources\utils\sharp\lib\operation.js:219:11)
    at C:\Users\xsy\.CocosCreator\packages\unpack-textureatlas\main.js:133:18
    at C:\CocosCreator\CocosCreator_v1.10.0-rc.1\resources\app.asar\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\CocosCreator\CocosCreator_v1.10.0-rc.1\resources\app.asar\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\CocosCreator\CocosCreator_v1.10.0-rc.1\resources\app.asar\node_modules\async\lib\async.js:209:22)
    at Object.unpack (C:\Users\xsy\.CocosCreator\packages\unpack-textureatlas\main.js:87:17)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at _main2main (C:\CocosCreator\CocosCreator_v1.10.0-rc.1\resources\app.asar\editor-framework\lib\main\ipc.js:1:2201)
    at Ipc.sendToMain (C:\CocosCreator\CocosCreator_v1.10.0-rc.1\resources\app.asar\editor-framework\lib\main\ipc.js:1:4010)
    at process.on.t (C:\CocosCreator\CocosCreator_v1.10.0-rc.1\resources\app.asar\editor\core\editor-init.js:1:360)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)

**Comment by fusijie** [comment]
好像是这个地方有问题

```
let trimmedLeft = Math.floor(offset.x + (originalSize.width - rect.width) / 2);
let trimmedRight = Math.ceil((originalSize.width - rect.width) / 2 - offset.x);
let trimmedTop = Math.ceil((originalSize.height - rect.height) / 2 - offset.y);
let trimmedBottom = Math.floor(offset.y + (originalSize.height - rect.height) / 2);
```

这几个trim值可能是0.5

**Comment by zilongshanren** [comment]
这个貌似有人提PR解决了。
